# Generated by Django 6.0.5 on 2026-05-12 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('code', models.CharField(db_index=True, max_length=16, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('synopsis', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveSmallIntegerField()),
                ('certification', models.CharField(choices=[('U', 'U'), ('UA', 'UA'), ('A', 'A'), ('S', 'S')], db_index=True, default='UA', max_length=8)),
                ('release_date', models.DateField(db_index=True)),
                ('trailer_url', models.URLField(blank=True, max_length=500)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='movie_posters/%Y/%m/')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genres', models.ManyToManyField(blank=True, related_name='movies', to='movies.genre')),
                ('languages', models.ManyToManyField(blank=True, related_name='movies', to='movies.language')),
            ],
            options={
                'ordering': ('-release_date', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('city', models.CharField(db_index=True, max_length=120)),
                ('address', models.TextField(blank=True)),
                ('pin_code', models.CharField(blank=True, max_length=16)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('total_screens', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('city', 'name'),
                'indexes': [models.Index(fields=['city', 'name'], name='movies_theater_city_name_idx'), models.Index(condition=models.Q(('is_active', True)), fields=['city'], name='movies_theater_city_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_label', models.CharField(default='Screen 1', max_length=64)),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seat_capacity', models.PositiveIntegerField(default=0)),
                ('is_cancelled', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='movies.movie')),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='movies.theater')),
            ],
            options={
                'ordering': ('starts_at',),
            },
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['title'], name='movies_movie_title_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['-release_date', 'title'], name='movies_movie_rel_title_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(condition=models.Q(('is_active', True)), fields=['release_date'], name='movies_movie_active_rel_dt_idx'),
        ),
        migrations.AddIndex(
            model_name='show',
            index=models.Index(fields=['theater', 'starts_at'], name='movies_show_thr_start_idx'),
        ),
        migrations.AddIndex(
            model_name='show',
            index=models.Index(fields=['movie', 'starts_at'], name='movies_show_movie_start_idx'),
        ),
        migrations.AddIndex(
            model_name='show',
            index=models.Index(condition=models.Q(('is_cancelled', False)), fields=['starts_at'], name='movies_show_upcoming_idx'),
        ),
        migrations.AddConstraint(
            model_name='show',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='movies_show_ends_after_starts'),
        ),
        migrations.AddConstraint(
            model_name='show',
            constraint=models.UniqueConstraint(fields=('theater', 'starts_at', 'screen_label'), name='movies_show_unique_screen_slot'),
        ),
    ]
