# Generated by Django 6.0.5 on 2026-05-13

from django.db import migrations, models


def create_through_indexes(apps, schema_editor):
    """
    Add PostgreSQL indexes on the implicit M2M through tables used for
    genre/language filtering. This keeps EXISTS/subquery filters index-friendly
    and prevents full table scans on large datasets.
    """
    if schema_editor.connection.vendor != "postgresql":
        return

    # Default through table names for:
    #   Movie.genres -> Genre    => movies_movie_genres
    #   Movie.languages -> Language => movies_movie_languages
    schema_editor.execute(
        "CREATE INDEX IF NOT EXISTS movies_movie_genres_genre_id_movie_id_idx "
        "ON movies_movie_genres (genre_id, movie_id);"
    )
    schema_editor.execute(
        "CREATE INDEX IF NOT EXISTS movies_movie_genres_movie_id_genre_id_idx "
        "ON movies_movie_genres (movie_id, genre_id);"
    )
    schema_editor.execute(
        "CREATE INDEX IF NOT EXISTS movies_movie_languages_language_id_movie_id_idx "
        "ON movies_movie_languages (language_id, movie_id);"
    )
    schema_editor.execute(
        "CREATE INDEX IF NOT EXISTS movies_movie_languages_movie_id_language_id_idx "
        "ON movies_movie_languages (movie_id, language_id);"
    )


def noop_reverse(apps, schema_editor):
    # Intentionally empty; indexes are additive and guarded by IF NOT EXISTS.
    return


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="rating",
            field=models.DecimalField(
                db_index=True, default=0, decimal_places=2, max_digits=4
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(fields=["-rating"], name="movies_movie_rating_desc_idx"),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["-rating", "-release_date", "title"],
                name="movies_movie_rating_rel_title_desc_idx",
            ),
        ),
        migrations.RunPython(create_through_indexes, reverse_code=noop_reverse),
    ]

