# Generated by Django 6.0.3 on 2026-05-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_rating_indexes_and_through_indexes'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='show',
            name='movies_show_ends_after_starts',
        ),
        migrations.RemoveConstraint(
            model_name='show',
            name='movies_show_unique_screen_slot',
        ),
        migrations.RenameIndex(
            model_name='movie',
            new_name='mv_title_idx',
            old_name='movies_movie_title_idx',
        ),
        migrations.RenameIndex(
            model_name='movie',
            new_name='mv_rating_idx',
            old_name='movies_movie_rating_desc_idx',
        ),
        migrations.RenameIndex(
            model_name='movie',
            new_name='mv_mix_idx',
            old_name='movies_movie_rating_rel_title_desc_idx',
        ),
        migrations.RenameIndex(
            model_name='movie',
            new_name='mv_date_idx',
            old_name='movies_movie_rel_title_idx',
        ),
        migrations.RenameIndex(
            model_name='movie',
            new_name='mv_active_idx',
            old_name='movies_movie_active_rel_dt_idx',
        ),
        migrations.RenameIndex(
            model_name='show',
            new_name='show_thr_idx',
            old_name='movies_show_thr_start_idx',
        ),
        migrations.RenameIndex(
            model_name='show',
            new_name='show_mv_idx',
            old_name='movies_show_movie_start_idx',
        ),
        migrations.RenameIndex(
            model_name='show',
            new_name='show_up_idx',
            old_name='movies_show_upcoming_idx',
        ),
        migrations.RenameIndex(
            model_name='theater',
            new_name='thr_city_idx',
            old_name='movies_theater_city_name_idx',
        ),
        migrations.RenameIndex(
            model_name='theater',
            new_name='thr_active_idx',
            old_name='movies_theater_city_active_idx',
        ),
        migrations.AddConstraint(
            model_name='show',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='show_time_chk'),
        ),
        migrations.AddConstraint(
            model_name='show',
            constraint=models.UniqueConstraint(fields=('theater', 'starts_at', 'screen_label'), name='show_unique_slot'),
        ),
    ]
